name: Publish to Crates.io

on:
  push:
    branches:
      - release
    tags:
      - 'v*'  # Optional: trigger on version tags

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: crates-io
    permissions:
      contents: read
      id-token: write  # Needed for GitHub OIDC auth if using it

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for version tagging

      - name: Setup Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable
          components: rustfmt, clippy  # Include useful components

      - name: Verify tag matches version
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          CRATE_VERSION=$(cargo pkgid | sed 's/.*#//')
          if [ "$TAG_VERSION" != "$CRATE_VERSION" ]; then
            echo "❌ Tag version $TAG_VERSION doesn't match crate version $CRATE_VERSION"
            exit 1
          fi

      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          # Only publish if we're on a tag or the release branch has new commits
          if [[ "$GITHUB_REF" == "refs/heads/release" ]] || [[ "$GITHUB_REF" == refs/tags/v* ]]; then
            cargo publish --token $CARGO_REGISTRY_TOKEN
          else
            echo "Skipping publish - not on release branch or version tag"
          fi