name: Auto Bump + Publish

on:
  push:
    branches:
      - release

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install cargo-edit (for version bumping)
        run: cargo install cargo-edit

      - name: Run pre-publish checks (fmt + test)
        run: make check

      - name: Auto bump patch version
        run: |
          CURRENT_VERSION=$(cargo pkgid | sed 's/.*#//')
          echo "Current version: $CURRENT_VERSION"
          cargo set-version --bump patch
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -am "chore: bump version to patch"
          git push

      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish --token $CARGO_REGISTRY_TOKEN

      - name: Tag release
        run: |
          VERSION=$(cargo pkgid | sed 's/.*#//')
          git tag v$VERSION
          git push origin v$VERSION
