name: Publish to Crates.io

on:
  push:
    branches: [release]
    tags: ['v*']

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: crates-io
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Publish to crates.io
        run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}